# Generated by Django 6.1.1 on 2026-09-25 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_inmobiliaria_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(null=True, verbose_name='Descripción')),
                ('www', models.URLField(null=True, verbose_name='WWW')),
                ('email', models.EmailField(max_length=100, null=True, verbose_name='Email')),
                ('telefono', models.CharField(max_length=20, null=True, verbose_name='Teléfono')),
                ('fecha_nacimiento', models.DateField(null=True, verbose_name='Fecha Nacimiento')),
                ('habilitado', models.BooleanField(default=True, verbose_name='Habilitado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización')),
            ],
            options={
                'db_table_comment': 'Autores de Propiedades.',
            },
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=5, verbose_name='Código')),
                ('comuna', models.CharField(max_length=60, verbose_name='Comuna')),
                ('habilitado', models.BooleanField(default=True, verbose_name='Habilitado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización')),
            ],
            options={
                'db_table_comment': 'Comunas de todo el mundo.',
            },
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.CharField(max_length=100, null=True, verbose_name='Calle')),
                ('numero', models.CharField(max_length=10, null=True, verbose_name='Número')),
                ('departamento', models.CharField(max_length=10, null=True, verbose_name='Dpto/Oficina')),
                ('habilitado', models.BooleanField(default=True, verbose_name='Habilitado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización')),
                ('comuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_inmobiliaria_app.comuna')),
            ],
            options={
                'db_table_comment': 'Direcciones de todo el mundo.',
            },
        ),
        migrations.CreateModel(
            name='Estado_Propiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('descripcion', models.TextField(null=True, verbose_name='Descripción')),
                ('habilitado', models.BooleanField(default=True, verbose_name='Habilitado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización')),
            ],
            options={
                'db_table_comment': 'Estados de Propiedades, como Disponible, Vendida, Alquilada, etc.',
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='País')),
                ('nacionalidad', models.CharField(max_length=30, verbose_name='Nacionalidad')),
                ('iso_2', models.CharField(max_length=2, verbose_name='ISO 2')),
                ('iso_3', models.CharField(max_length=3, verbose_name='ISO 3')),
                ('habilitado', models.BooleanField(default=True, verbose_name='Habilitado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización')),
            ],
            options={
                'db_table_comment': 'Información de paises del mundo, para asociar a autores de Propiedad.',
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=3, verbose_name='Código')),
                ('provincia', models.CharField(max_length=50, verbose_name='Provincia')),
                ('habilitado', models.BooleanField(default=True, verbose_name='Habilitado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización')),
            ],
            options={
                'db_table_comment': 'Provincias de todo el mundo.',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=2, verbose_name='Código')),
                ('region', models.CharField(max_length=30, verbose_name='Región')),
                ('habilitado', models.BooleanField(default=True, verbose_name='Habilitado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización')),
            ],
            options={
                'db_table_comment': 'Regiones de todo el mundo.',
            },
        ),
        migrations.CreateModel(
            name='ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Latitud')),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Longitud')),
                ('habilitado', models.BooleanField(default=True, verbose_name='Habilitado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización')),
            ],
            options={
                'db_table_comment': 'Ubicación de Propiedades en el mapa.',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='Email')),
                ('telefono', models.CharField(max_length=20, null=True, verbose_name='Teléfono')),
                ('habilitado', models.BooleanField(default=True, verbose_name='Habilitado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización')),
            ],
            options={
                'db_table_comment': 'Usuarios del sistema de gestión inmobiliaria.',
            },
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='Dueño',
        ),
        migrations.AlterModelTableComment(
            name='propiedad',
            table_comment='Propiedades de todo el mundo.',
        ),
        migrations.RemoveField(
            model_name='propiedad',
            name='fecha_publicacion',
        ),
        migrations.RemoveField(
            model_name='propiedad',
            name='precio',
        ),
        migrations.AddField(
            model_name='propiedad',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha Creación'),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='habilitado',
            field=models.BooleanField(default=True, verbose_name='Habilitado'),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre'),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='tipo',
            field=models.CharField(blank=True, choices=[('Casa', 'Casa'), ('Departamento', 'Departamento'), ('Oficina', 'Oficina'), ('Local Comercial', 'Local Comercial'), ('Terreno', 'Terreno')], max_length=20, null=True, verbose_name='Tipo'),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha Actualización'),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_inmobiliaria_app.autor'),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='direccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_inmobiliaria_app.direccion'),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='estado_Propiedad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_inmobiliaria_app.estado_propiedad'),
        ),
        migrations.AddField(
            model_name='autor',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_inmobiliaria_app.pais'),
        ),
        migrations.AddField(
            model_name='comuna',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_inmobiliaria_app.provincia'),
        ),
        migrations.AddField(
            model_name='provincia',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_inmobiliaria_app.region'),
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='propiedad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_inmobiliaria_app.propiedad'),
        ),
    ]
